# Generated by Django 5.0 on 2024-02-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_delete_profileinfo_remove_task_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
